### ISSUE TITLE
Virtual platform configuration without matrix definitions

### ISSUE THREAD

**Issue by lriesebos** [QuTech-Delft/OpenQL#123]
A configuration file for virtual platforms (eqasm_compiler = none) requires every instruction to have a matrix definition. If these JSON attributes would not be obligatory anymore, the configuration file will be simplified and reduced in size.

Proposed solution:
Make instruction matrix definitions optional for at least virtual platforms.

**Comment by wvlothuizen** [comment]
Implemented in 0.10.0
