### ISSUE TITLE
Stable production pipeline

### ISSUE THREAD

**Issue by AdriaanRol** [QuTech-Delft/OpenQL#160]
From meeting with @imranashraf , @Nader-Khammassi @slavoutich : 

This issue is intended to refer to other issues to ensure a stable deployment of versions. 
Everything here relates to preventing problems when installing and upgrading OpenQL. 

- [ ] Auto generated documentation by `Sphinx` + hosted on website 
- [ ] Decide on documentation formatting convention (`NumpyDoc`) 
- [ ] Test build status clearly visible on repository 
- [ ] Tests can be only added, not removed (ensures regression tests) 
- [ ] Ensure tests happen against the Assembler (and be clear about the version) 
- [ ] Clear release notes 
- [ ] No backwards incompatible changes to API, unless: 
     - [ ] Legacy support for last x-versions (keep old version with deprecation warnings)
     - [ ] Clearly documented in release notes

**Comment by wvlothuizen** [comment]
Mostly implemented in 0.10.0
