### ISSUE TITLE
Unclear error message, `TypeError: [x] error : ql::eqasm_compiler::compile() : error while reading hardware settings : invalid 'cc_light_instr_type' for instruction !`

### ISSUE THREAD

**Issue by AdriaanRol** [QuTech-Delft/OpenQL#162]
When the hardware config.json file contains an instruction that is not valid the following error is raised: 
`TypeError: [x] error : ql::eqasm_compiler::compile() : error while reading hardware settings : invalid 'cc_light_instr_type' for instruction !`

This error makes it impossible to find out what the offending instruction is as it does not say which instruction is the problem or on which line the error occurs.

**Comment by wvlothuizen** [comment]
Solved long ago
