### ISSUE TITLE
Documentation on core concepts (Program, Subprogram?, Kernel)

### ISSUE THREAD

**Issue by AdriaanRol** [QuTech-Delft/OpenQL#167]
In a program containing classical logic sub programs are added to programs as well as kernels. 

The paradigm in which this should work is not documented. I remember we had a discussion several months ago where we discussed ways in which this could work and how we should be using this. It is very challenging to infer these ideas from the minimal example in the provided example notebook.

**Comment by wvlothuizen** [comment]
documentation added long ago
