### ISSUE TITLE
Description of arbitrary rotations in the configuration file is not understood

### ISSUE THREAD

**Issue by Gonaco** [QuTech-Delft/OpenQL#188]
After describing a rotation gate in the configuration file like this:

```
"ry": {
      "duration": 20,
      "latency": 0,
      "matrix": [ [0.0,1.0], [1.0,0.0], [1.0,0.0], [0.0,0.0] ],
      "disable_optimization": false,
      "type": "mw",
      "cc_light_instr_type": "single_qubit_gate",
      "cc_light_instr": "y90",
      "cc_light_opcode": 14
   }
```

and using it in an alias decomposition in the configuration file as well

```
"cnot_real %0 %1": ["ry %1, -90","cz %0 %1","ry %1, 90"]

```
OpenQL confuses the rotation parameter -- that is a classical register (-/+ 90) -- with a quantum register. This results in a compilation failure.

**Comment by wvlothuizen** [comment]
Now supported by new-style decomposition
