### ISSUE TITLE
Developers documentation

### ISSUE THREAD

**Issue by imranashraf** [QuTech-Delft/OpenQL#213]
general documentation, as well as specific example for the addition of a feature should be provided

**Comment by MiguelSMoreira** [comment]
Progress on this issue should include a first draft of _Developers Documentation_ that should focus on the aspects of OpenQL most relevant for a programmer/developer of OpenQL. The sooner a first version is ready, the sooner we will be able to iterate on what this document should contain, to converge on this issue
