### ISSUE TITLE
Documentation on the effects of constraints in scheduling

### ISSUE THREAD

**Issue by AdriaanRol** [QuTech-Delft/OpenQL#254]
Apart from general information on the effects of constraints in scheduling, we are particularly interested in documenting how hand-scheduling (use of barrier() calls in OpenQL to bypass reordering of operations done by the compiler) can be done without hardware constraints specified in OpenQL's configuration file having an effect on the timing of operations.

It may also be worthwhile to consider new ways to use OpenQL such that the aforementioned features in the scheduler (the ones we attempt to avoid using barrier() calls) are bypassed. This may lead to faster, more efficient, compilation.

**Comment by MiguelSMoreira** [comment]
Apart from general information on the effects of constraints in scheduling, we are particularly interested in documenting how hand-scheduling (use of barrier() calls in OpenQL to bypass reordering of operations done by the compiler) can be done without hardware constraints specified in OpenQL's configuration file having an effect on the timing of operations.

It may also be worthwhile to consider new ways to use OpenQL such that the aforementioned features in the scheduler (the ones we attempt to avoid using barrier() calls) are bypassed. This may lead to faster, more efficient, compilation.
