### ISSUE TITLE
Support for control-flow feedback

### ISSUE THREAD

**Issue by MiguelSMoreira** [QuTech-Delft/OpenQL#384]
This issue shall serve to keep track of ideas, discussions and updates regarding the design and implementation of better constructs to describe control-flow feedback in both cQASM and the OpenQL API Interface.

**Comment by jvanstraten** [comment]
For cQASM, we now have cQASM 1.2 support in libqasm. The idea would be to implement that in OpenQL as well, while redesigning the IR to be more sane. Details for what was added in 1.2 can be read at https://github.com/QE-Lab/libqasm/pull/127.

**Comment by MiguelSMoreira** [comment]
The specific case of repeat-until-success circuits compiled using cqasm 1.2 should be tested

**Comment by MiguelSMoreira** [comment]
Firmware and software have been upgraded in the Lamborghini. 
For this test to be completed, a sequence of cqasm 1.2 shall be provided to replicate previous functionality with repeat-until-success circuits

**Comment by wvlothuizen** [comment]
Control-flow feedback now exists
