### ISSUE TITLE
(CI for) Conda on windows-2016 is broken

### ISSUE THREAD

**Issue by jvanstraten** [QuTech-Delft/OpenQL#388]
Not sure if something externally dropped support for something or if it only worked accidentally before.

**Comment by jvansomeren** [comment]
The failing test seems to be systematic: conda windows-2016 failed also this afternoon.
It tries to initialize for x64 in a batch file just right after having entered visual studio
and exits from that batch file.


Op 10 feb. 2021, om 15:05 heeft jvanstraten <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:



Not sure if something externally dropped support for something or if it only worked accidentally before.

**Comment by wvlothuizen** [comment]
Conda is disabled in 0.10.0
