### ISSUE TITLE
Kernel creation from QX-Compatible QASM v1.0 Files

### ISSUE THREAD

**Issue by Nader-Khammassi** [QuTech-Delft/OpenQL#66]
Creating kernels from QASM 1.0 files is very useful for:
  - Testing the validity of the OpenQL QASM output to make sure the syntax is correct and works with the QX simulator.
  - Reading QASM Code from other Tools.
  - Reading / Writing Intermediate QASM Output between the  Compiler Passes (Debugging / Testing).
  - ... etc

Kernel can then be created as following:
_kernel k("file.qasm")_

**Comment by Astlaan** [comment]
Is there already a way to create a kernel from a cqasm file?

**Comment by Astlaan** [comment]
Just leaving a reminder here, since this is really important.

**Comment by wvlothuizen** [comment]
supported by cQASM reader
